services:
  db:
    image: postgres
    container_name: foodhub-db
    environment:
      POSTGRES_USER: ${PRIVATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRIVATE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRIVATE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Web UI (optional)
    environment:
      - MINIO_ROOT_USER=${PRIVATE_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${PRIVATE_MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - foodhub-net

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - http_proxy=
      - https_proxy=
      - no_proxy=minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 ${PRIVATE_MINIO_ROOT_USER} ${PRIVATE_MINIO_ROOT_PASSWORD};
      mc mb myminio/foodhub;
      mc anonymous set public myminio/foodhub;
      exit 0;
      "
    networks:
      - foodhub-net

volumes:
  postgres_data:
  minio_data:

networks:
  foodhub-net: